name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress tests
        uses: ./
        with:
##          working-directory: examples/v9/basic
          build: npx cypress info
